### ISSUE TITLE
process bash failed

### ISSUE THREAD

**Issue by andy5995** [vmactions/openbsd-vm#13]
Before I start messing with my workflow, just wanted to ask did the location of bash move or do I just need to explicity install it? ([Using v1 now](https://github.com/theimpossibleastronaut/rmw/pull/410).)

https://github.com/theimpossibleastronaut/rmw/actions/runs/6853398435/job/18634119120?pr=410#step:3:758

```
  Error: The process '/bin/bash' failed with exit code 1
  Error: The process '/bin/bash' failed with exit code 1
```

**Comment by macie** [comment]
Output of this action is quite messy. You don't have a problem with bash - the real error is [a few lines above](https://github.com/theimpossibleastronaut/rmw/actions/runs/6853398435/job/18634119120?pr=410#step:3:729):

```
  error: failed to connect to the hypervisor
  error: Failed to connect socket to '/Users/runner/.cache/libvirt/virtqemud-sock': No such file or directory
```

So it looks like something went wrong with vm.

**Comment by macie** [comment]
@andy5995 [you have](https://github.com/theimpossibleastronaut/rmw/blob/cd9df810daec84430b34ace308acf79e7e91068f/.github/workflows/c-cpp.yml#L139):

```yaml
  openbsd:
    runs-on: macos-12
    name: A job to run test in OpenBSD
```

but `README.md` [says](https://github.com/theimpossibleastronaut/rmw/blob/cd9df810daec84430b34ace308acf79e7e91068f/.github/workflows/c-cpp.yml#L139), that in v1 it should be:

```yaml
  openbsd:
    runs-on: ubuntu-22.04
    name: A job to run test in OpenBSD
```
---
Adding a section in `README.md` with migration guide v0 → v1 may be a good idea.
